firstCompareCandidateDir  : /home/yyang/projects/mail-routing-ui/frontend/pre_screenshoots/screenshots/firefox
secondCompareCandidateDir : /home/yyang/projects/mail-routing-ui/frontend/after_screenshots
outPutDir : /home/yyang/projects/mail-routing-ui/frontend/result/
pathOfDataJs : /home/yyang/playground/com-aconex-yang-img-comparator/src/main/resources/data.js